### ISSUE TITLE
Website Title

### ISSUE THREAD

**Issue by jithin-j** [jithin-j/AirBnb-Experiences-Clone#1]
- Change the website title from 'React App' to 'AirBnB-Experiences-Clone'
- Add a new favicon for the app

**Comment by RahulSankhla312** [comment]
Hey @jithin-j  could you please assign this issue to me.

**Comment by codeships** [comment]
can assign me to this please

**Comment by Yh010** [comment]
I would like to work on this issue. Could u pls assign this issue?

**Comment by jithin-j** [comment]
Required changes have been made. Thank you.
