### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by jithin-j** [jithin-j/AirBnb-Experiences-Clone#3]
- Create a mobile responsive footer for the website.

**Comment by RahulSankhla312** [comment]
Hello @jithin-j could you please assign this issue to me.

**Comment by pscon** [comment]
Hey, I just saw your issue @jithin-j , and I would love to help you on this one !

**Comment by RahulSankhla312** [comment]
@jithin-j i have added the footer .

**Comment by jithin-j** [comment]
> @jithin-j i have added the footer .

Thanks for the contribution!
